DROP DATABASE IF EXISTS company_data;
CREATE DATABASE company_data;
USE company_data;

DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS employee;

CREATE TABLE department (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30)
);

CREATE TABLE role (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30),
salary DECIMAL,
department_ID INTEGER,
 FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE SET NULL
);

CREATE TABLE employee (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30),
last_name DECIMAL,
role_id INTEGER,
manager_id INTEGER,
FOREIGN KEY (manager_id) REFERENCES employee(id) ON DELETE SET NULL
);